// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {MockERC20} from "../test/mocks/MockERC20.sol";
import {TradeInfraEscrow} from "../src/core/TradeInfraEscrow.sol";
import {CentralizedTradeOracle} from "../src/CentralizedTradeOracle.sol";
import {CredenceReceivable} from "../src/CredenceReceivable.sol";

/// @title Deploy Mock Tokens for Testnet
/// @notice Deploys MockUSDC, MockUSDT, MockWETH and mints 1M tokens to each wallet
/// @dev Wallets: BUYER, SELLER, FEE_RECIPIENT, ARBITER, PROTOCOL_ARBITER, ORACLE_OWNER
contract DeployMockTokens is Script {
    // Amount to mint to each wallet (1,000,000 tokens)
    // USDC/USDT: 6 decimals -> 1_000_000 * 10^6 = 1_000_000_000_000
    // WETH: 18 decimals -> 1_000_000 * 10^18 = 1_000_000_000_000_000_000_000_000
    uint256 constant MINT_AMOUNT_6DEC = 1_000_000_000_000;
    uint256 constant MINT_AMOUNT_18DEC = 1_000_000_000_000_000_000_000_000;

    function run() external {
        uint256 deployerPrivateKey = vm.envOr(
            "PRIVATE_KEY",
            uint256(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80)
        );

        vm.startBroadcast(deployerPrivateKey);

        // 1. Deploy MockUSDC (6 decimals)
        MockERC20 usdc = new MockERC20("Mock USDC", "USDC", 6);
        console.log("MockUSDC deployed at:", address(usdc));

        // 2. Deploy MockUSDT (6 decimals)
        MockERC20 usdt = new MockERC20("Mock USDT", "USDT", 6);
        console.log("MockUSDT deployed at:", address(usdt));

        // 3. Deploy MockWETH (18 decimals)
        MockERC20 weth = new MockERC20("Mock WETH", "WETH", 18);
        console.log("MockWETH deployed at:", address(weth));

        // Wallets to receive tokens
        address buyer = vm.envAddress("BUYER");
        address seller = vm.envAddress("SELLER");
        address feeRecipient = vm.envAddress("FEE_RECIPIENT");
        address arbiter = vm.envAddress("ARBITER");
        address protocolArbiter = vm.envAddress("PROTOCOL_ARBITER");
        address oracleOwner = vm.envAddress("ORACLE_OWNER");
        address deployer = vm.addr(deployerPrivateKey);

        address[] memory recipients = new address[](6);
        recipients[0] = buyer;
        recipients[1] = seller;
        recipients[2] = feeRecipient;
        recipients[3] = arbiter;
        recipients[4] = protocolArbiter;
        recipients[5] = deployer;

        // 4. Mint USDC to all recipients
        console.log("\nMinting USDC...");
        for (uint256 i = 0; i < recipients.length; i++) {
            usdc.mint(recipients[i], MINT_AMOUNT_6DEC);
            console.log(string.concat("  Minted 1,000,000 USDC to: "), _toHexString(recipients[i]));
        }

        // 5. Mint USDT to all recipients
        console.log("\nMinting USDT...");
        for (uint256 i = 0; i < recipients.length; i++) {
            usdt.mint(recipients[i], MINT_AMOUNT_6DEC);
            console.log(string.concat("  Minted 1,000,000 USDT to: "), _toHexString(recipients[i]));
        }

        // 6. Mint WETH to all recipients
        console.log("\nMinting WETH...");
        for (uint256 i = 0; i < recipients.length; i++) {
            weth.mint(recipients[i], MINT_AMOUNT_18DEC);
            console.log(string.concat("  Minted 1,000,000 WETH to: "), _toHexString(recipients[i]));
        }

        vm.stopBroadcast();

        // 7. Now deploy the Escrow and wire everything
        console.log("\n=== Deploying Escrow System ===");
        
        vm.startBroadcast(deployerPrivateKey);

        // Deploy Oracle
        CentralizedTradeOracle oracle = new CentralizedTradeOracle(oracleOwner);
        console.log("CentralizedTradeOracle deployed at:", address(oracle));

        // Deploy Escrow
        TradeInfraEscrow escrow = new TradeInfraEscrow(address(oracle), feeRecipient, protocolArbiter);
        console.log("TradeInfraEscrow deployed at:", address(escrow));

        // Deploy Receivable
        CredenceReceivable receivable = new CredenceReceivable(address(escrow));
        escrow.setReceivableMinter(address(receivable));
        console.log("CredenceReceivable deployed at:", address(receivable));

        // Whitelist mock tokens in escrow
        escrow.addApprovedToken(address(usdc));
        escrow.addApprovedToken(address(usdt));
        escrow.addApprovedToken(address(weth));
        escrow.addApprovedToken(address(0)); // Native ETH
        console.log("Whitelisted: USDC, USDT, WETH, ETH");

        vm.stopBroadcast();

        // Write .env.mocks file
        string memory envContent = string.concat(
            "# Mock Tokens Deployment Output\n",
            "# Generated by DeployMockTokens.s.sol\n\n",
            "MOCK_USDC_ADDRESS=",
            _toHexString(address(usdc)),
            "\n",
            "MOCK_USDT_ADDRESS=",
            _toHexString(address(usdt)),
            "\n",
            "MOCK_WETH_ADDRESS=",
            _toHexString(address(weth)),
            "\n"
        );

        vm.writeFile(".env.mocks", envContent);

        // Summary
        console.log("\n=== Deployment Summary ===");
        console.log("MockUSDC: ", address(usdc));
        console.log("MockUSDT: ", address(usdt));
        console.log("MockWETH: ", address(weth));
        console.log("Escrow:   ", address(escrow));
        console.log("Oracle:  ", address(oracle));
        console.log("Receivable: ", address(receivable));
        console.log("==============================");
        console.log("Minted to 6 wallets:");
        console.log("  - BUYER           ", buyer);
        console.log("  - SELLER           ", seller);
        console.log("  - FEE_RECIPIENT    ", feeRecipient);
        console.log("  - ARBITER          ", arbiter);
        console.log("  - PROTOCOL_ARBITER ", protocolArbiter);
        console.log("  - DEPLOYER         ", deployer);
        console.log("\nEach wallet received:");
        console.log("  - 1,000,000 USDC (6 decimals)");
        console.log("  - 1,000,000 USDT (6 decimals)");
        console.log("  - 1,000,000 WETH (18 decimals)");
    }

    function _toHexString(address addr) internal pure returns (string memory) {
        bytes32 b = bytes32(uint256(uint160(addr)));
        bytes memory hexChars = "0123456789abcdef";
        bytes memory str = new bytes(42);
        str[0] = "0";
        str[1] = "x";
        for (uint256 i = 0; i < 20; i++) {
            str[2 + i * 2] = hexChars[uint8(b[i + 12] >> 4)];
            str[3 + i * 2] = hexChars[uint8(b[i + 12] & 0x0f)];
        }
        return string(str);
    }
}
